theme: jekyll-theme-minimal 
title: ğŸ¯ Website | Blog | FNET00â„¢ ğŸŒ¿
description: FNET00 is an educational blog and website, filtering and free internet access..!ğŸš€ğŸ¯
url: "https://FNET00Bot.github.io" 
